---
services:
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        ENABLED_MODULES: headers-more
    environment:
      - WG_PORT_PROXY=${WG_PORT}
      - NGINX_DOMAIN=${NGINX_DOMAIN}
      - ALLOWED_NGINX_IPS=${ALLOWED_NGINX_IPS}
    image: nginx-hm:1.27-alpine
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
      - '${WG_PORT}:51819/udp'
    volumes:
      - '../nginx.conf:/etc/nginx/nginx.conf'
      - '../templates:/etc/nginx/templates/'
      - '../certs:/etc/nginx/ssl/'
    networks:
      local-network:
        ipv4_address: 172.16.238.4
    depends_on:
      - wg_easy
    restart: unless-stopped

  wg_easy:
    environment:
      - LANG=${WG_LANGUAGE}
      - WG_HOST=${WG_HOST}
      - PASSWORD_HASH=${PASSWORD_HASH}
      - PORT=${WEB_INTERFACE_PORT}
      - WG_PORT=${WG_PORT}
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_SUBNET}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
      - WG_MTU=${WG_MTU}
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS}
      - UI_TRAFFIC_STATS=${WG_UI_TRAFFIC_STATS}
      - UI_CHART_TYPE=3
    image: 'ghcr.io/wg-easy/wg-easy:14@sha256:5f26407fd2ede54df76d63304ef184576a6c1bb73f934a58a11abdd852fab549'
    container_name: wg-easy
    volumes:
      - '/etc/wireguard:/etc/wireguard'
    networks:
      local-network:
        ipv4_address: 172.16.238.5
    ports:
      - '172.16.238.1:${WEB_INTERFACE_PORT}:${WEB_INTERFACE_PORT}/tcp'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  local-network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1

volumes:
  etc_wireguard:
