---
version: '3.0'
services:
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        ENABLED_MODULES: headers-more
    environment:
      - 'WG_PORT_PROXY=${WG_PORT}'
    image: nginx-hm:1.27-alpine
    ports:
      - '80:80'
      # - '443:443'
      - '${WG_PORT}:51819/udp'
    volumes:
      - '../nginx.conf:/etc/nginx/nginx.conf'
      - '../templates:/etc/nginx/templates/'
    networks:
      local-network:
        ipv4_address: 172.16.238.4
    depends_on:
      - wg_easy
    restart: unless-stopped

  wg_easy:
    environment:
      - LANG=en
      - 'WG_HOST=${WG_HOST}'
      - PASSWORD=${PASSWORD}
      - 'PORT=${WEB_PORT}'
      - 'WG_PORT=${WG_PORT}'
      - WG_DEFAULT_ADDRESS=10.16.0.x
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_MTU=1420
      - WG_PERSISTENT_KEEPALIVE=25
      # - WG_ALLOWED_IPS=10.16.0.0/24
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=3
    image: 'ghcr.io/wg-easy/wg-easy:13@sha256:24eddefd4e5ae2cff930d4f9254f018d5f4cdd48daf559e7a73a14da6a9fbbb4'
    container_name: wg-easy
    volumes:
      - '/etc/wireguard:/etc/wireguard'
    networks:
      local-network:
        ipv4_address: 172.16.238.5
    ports:
      - '172.16.238.1:${WEB_PORT}:${WEB_PORT}/tcp'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  local-network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1

volumes:
  etc_wireguard:

# volumes:
#   grafana-storage:
#     name: "grafana-storage"
#     external: true
#   grafana-config:
#     name: "grafana-config"
#     external: true
