---
version: "3.0"
services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      - LANG=en
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=${WG_HOST}

      # Optional:
      - PASSWORD=
      - PORT=${PORT}
      - WG_PORT=${WG_PORT}
      - WG_DEFAULT_ADDRESS=10.16.0.x
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=3  # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    build:
      dockerfile: ${PWD}/Dockerfile
      args:
        version: ${IMAGE_VERSION}
      context: /
    image: custom-wg-easy:${IMAGE_VERSION}
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    networks:
      local-network:
        ipv4_address: 172.16.238.5
    ports:
      - "${WG_PORT}:${WG_PORT}/udp"
      - "${PORT}:${PORT}/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  local-network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
          # - subnet: "2001:3984:3989::/64"
          gateway: "172.16.238.1"

volumes:
  etc_wireguard:

# volumes:
#   grafana-storage:
#     name: "grafana-storage"
#     external: true
#   grafana-config:
#     name: "grafana-config"
#     external: true
